/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ITowerlordsCards__factory } from "./ITowerlordsCards__factory";
export { TowerlordsPack__factory } from "./TowerlordsPack__factory";
