/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ITowerlordsCards,
  ITowerlordsCardsInterface,
} from "../../../contracts/TowerlordsPack.sol/ITowerlordsCards";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "string",
        name: "cardDefinitionId",
        type: "string",
      },
    ],
    name: "mintCard",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "minter",
        type: "address",
      },
    ],
    name: "setMinter",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ITowerlordsCards__factory {
  static readonly abi = _abi;
  static createInterface(): ITowerlordsCardsInterface {
    return new Interface(_abi) as ITowerlordsCardsInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ITowerlordsCards {
    return new Contract(address, _abi, runner) as unknown as ITowerlordsCards;
  }
}
