/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as towerlordsPackSol from "./TowerlordsPack.sol";
export type { towerlordsPackSol };
export type { TowerlordsCards } from "./TowerlordsCards";
