/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ITowerlordsCards } from "./ITowerlordsCards";
export type { TowerlordsPack } from "./TowerlordsPack";
